// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2B3lqw5gbnaSN2Riri--2n1q9kyGftMM',
    appId: '1:865295307417:web:2984835af8e628d67a9e08',
    messagingSenderId: '865295307417',
    projectId: 'inataclone-3',
    authDomain: 'inataclone-3.firebaseapp.com',
    storageBucket: 'inataclone-3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-Ao77ZyspTmrql_qNaX8kVppIa5lpnE',
    appId: '1:865295307417:android:e594bd488c6686b97a9e08',
    messagingSenderId: '865295307417',
    projectId: 'inataclone-3',
    storageBucket: 'inataclone-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdjWsHMG20NOFj95RALdy2hWgobxAUgaI',
    appId: '1:865295307417:ios:aaf2f7611d6463237a9e08',
    messagingSenderId: '865295307417',
    projectId: 'inataclone-3',
    storageBucket: 'inataclone-3.appspot.com',
    iosClientId: '865295307417-9315lf48a8ugpkkh1kavrn7giso82lar.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdjWsHMG20NOFj95RALdy2hWgobxAUgaI',
    appId: '1:865295307417:ios:670943a4f86065d07a9e08',
    messagingSenderId: '865295307417',
    projectId: 'inataclone-3',
    storageBucket: 'inataclone-3.appspot.com',
    iosClientId: '865295307417-nejb5q6tdssk93821c6ubuujf28taqdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone.RunnerTests',
  );
}
